#This configuration file will hold common configs to be shared among all files
eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://10.191.90.127:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://10.191.90.127:8080/uaa/user/current
      token-info-uri: http://10.191.90.127:8080/uaa/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG
